language: r
sudo: required

warnings_are_errors: true

env:
  - NOT_CRAN=true

r_github_packages:
  - jimhester/covr
  
after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: always